gcp_region                = "europe-north1"
gcp_zone                  = "europe-north1-a"
project_name              = "domain1"
project_id                = "sixth-beaker-366215"
project_subnet_self_link  = "https://www.googleapis.com/compute/v1/projects/sixth-beaker-366215/regions/europe-north1/subnetworks/domain1"
